### ISSUE TITLE
pydantic version 2.10.2 breaks chainlit

### ISSUE THREAD

**Issue by kkcheng0816** [AI-Maker-Space/The-AI-Engineer-Challenge#4]
After running "pip install -r requirements.txt", the command "chainlit hello" hit the following error. 

Traceback (most recent call last):

  File "/opt/anaconda3/envs/beyond-chatgpt/bin/chainlit", line 5, in <module>

    from chainlit.cli import cli

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/chainlit/__init__.py", line 20, in <module>

    import chainlit.input_widget as input_widget

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/chainlit/input_widget.py", line 5, in <module>

    from chainlit.types import InputWidgetType

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/chainlit/types.py", line 5, in <module>

    from chainlit.element import File

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/chainlit/element.py", line 11, in <module>

    from chainlit.context import context

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/chainlit/context.py", line 6, in <module>

    from chainlit.session import HTTPSession, WebsocketSession

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/chainlit/session.py", line 10, in <module>

    from chainlit.data import chainlit_client

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/chainlit/data/__init__.py", line 5, in <module>

    from chainlit.config import config

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/chainlit/config.py", line 357, in <module>

    config = load_config()

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/chainlit/config.py", line 341, in load_config

    settings = load_settings()

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/chainlit/config.py", line 319, in load_settings

    "code": CodeSettings(action_callbacks={}),

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/pydantic/_internal/_dataclasses.py", line 121, in __init__

    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)

  File "/opt/anaconda3/envs/beyond-chatgpt/lib/python3.9/site-packages/pydantic/_internal/_mock_val_ser.py", line 100, in __getattr__

    raise PydanticUserError(self._error_message, code=self._code)

pydantic.errors.PydanticUserError: `CodeSettings` is not fully defined; you should define `Action`, then call `pydantic.dataclasses.rebuild_dataclass(CodeSettings)`.

For further information visit https://errors.pydantic.dev/2.10/u/class-not-fully-defined

**Comment by kkcheng0816** [comment]
Adding the following line in requirements.txt solved the above issue.
pydantic==2.10.1

**Comment by toddllm** [comment]
@chris-alexiuk
